[package]
name = "kana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kana-macros = { path = "../kana-macros" }

[dev-dependencies]
tux = { version = "0.2" }
